# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: soundmanager2-rails 2.97.20170601 ruby lib

Gem::Specification.new do |s|
  s.name = "soundmanager2-rails".freeze
  s.version = "2.97.20170601"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Sudara".freeze]
  s.date = "2017-06-18"
  s.description = "Exposes soundmanager2 as a vendored js lib in rails 3 ".freeze
  s.email = "sudara@alonetone.com".freeze
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/soundmanager2-rails.rb",
    "soundmanager2-rails.gemspec",
    "vendor/assets/javascripts/soundmanager2-jsmin.js",
    "vendor/assets/javascripts/soundmanager2-nodebug-jsmin.js",
    "vendor/assets/javascripts/soundmanager2-nodebug.js",
    "vendor/assets/javascripts/soundmanager2.js",
    "vendor/assets/javascripts/soundmanager2.swf",
    "vendor/assets/javascripts/soundmanager2_debug.swf",
    "vendor/assets/javascripts/soundmanager2_flash9.swf",
    "vendor/assets/javascripts/soundmanager2_flash9_debug.swf"
  ]
  s.homepage = "http://github.com/sudara/soundmanager2-rails".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Exposes soundmanager2 as a vendored js lib in rails 3".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    else
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

